# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "PyYAML" = super.buildPythonPackage rec {
    pname = "PyYAML";
    version = "6.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cd/e5/af35f7ea75cf72f2cd079c95ee16797de7cd71f29ea7c68ae5ce7be1eda0/PyYAML-6.0.1.tar.gz";
      sha256 = "0hsa7g6ddynifrwdgadqcx80khhblfy94slzpbr7birn2w5ldpxz";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "colorama" = super.buildPythonPackage rec {
    pname = "colorama";
    version = "0.4.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/77/8b/7550e87b2d308a1b711725dfaddc19c695f8c5fa413c640b2be01662f4e6/colorama-0.4.5-py2.py3-none-any.whl";
      sha256 = "1nlriqsqjsilvxg6pm3086z2xkjviplw3gz79a1gadryjd2g8jw5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "setuptools-scm" = super.buildPythonPackage rec {
    pname = "setuptools-scm";
    version = "2.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4d/a0/371355cbd608ef1d865738b94f7681e2fe56ef951070a66a892f30042a86/setuptools_scm-2.1.0-py2.py3-none-any.whl";
      sha256 = "10dpxhdb4jwxx7z2pvb6q1fxxhmqdj49cqfb0i6mxb7mvr4gnq8j";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "vsg" = super.buildPythonPackage rec {
    pname = "vsg";
    version = "3.22.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4c/ee/fc7d0198fc4a3f41d78d2606a85bea0c54a51c53f75c827eb5aac9ca42e3/vsg-3.22.0.tar.gz";
      sha256 = "0y1xn5b8zr9hydpnplzb96v5jnxkaw61dygasi508rbcfhdni6jq";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."PyYAML"
    ];
  };
  "vunit-hdl" = super.buildPythonPackage rec {
    pname = "vunit-hdl";
    version = "4.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/4e/bb6c6c1aaccc19f5ebd261fa241a044b501a3704dcb8103b769335badbc4/vunit_hdl-4.7.0.tar.gz";
      sha256 = "0bgj31fzsa9vk09303k57smlkxnqyk2vs3bfjr8shbmxpa8vjpx2";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools"
      self."setuptools-scm"
    ];
    propagatedBuildInputs = [
      self."colorama"
    ];
  };
}
